development:
  adapter: postgresql
  encoding: unicode
  database: buffalo_development
  pool: 5
  timeout: 5000
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: buffalo_test
  pool: 5
  timeout: 5000
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: buffalo_production
  pool: 5
  timeout: 5000
  password:

cucumber:
  <<: *test
